Repository NCAR/geocat-comp, pull requests merged in 2021-02, with the labels that each got.

#93 Relhum
  .gitignore
  src/geocat/comp/relhum.py
  test/test_relhum.py
Labels: enhancement, ready for review

#95 Dewtemp
  .gitignore
  docs/internal_api/index.rst
  docs/user_api/index.rst
  src/geocat/comp/__init__.py
  src/geocat/comp/dewtemp.py
  src/geocat/comp/relhum.py
  test/test_dewtemp.py
Labels: ready for review

#105 Relhum release prep
  src/geocat/comp/__init__.py
  src/geocat/comp/dewtemp.py
  src/geocat/comp/relhum.py
  test/test_relhum.py
Labels: bug, ready for review

#107 Repo-specific documentation update for GeoCAT-f2py vs GeoCAT-ncomp
  CONTRIBUTING.md
  INSTALLATION.md
  README.md
  docs/conf.py
  setup.py
  src/geocat/comp/climatology.py
  src/geocat/comp/eofunc.py
  test/test_climatology.py
  test/test_eofunc.py
  test/test_relhum.py
Labels: ready for review
