Repository NCAR/geocat-comp, pull requests merged in 2023-01, with the labels that each got.

#315 Add `keep_attrs` to functions
  src/geocat/comp/climatologies.py
  test/test_climatologies.py
Labels: ready for review

#332 Replace and deprecate `anomaly`
  docs/user_api/index.rst
  src/geocat/comp/__init__.py
  src/geocat/comp/climatologies.py
  test/test_climatologies.py
Labels: bug

#335 Allow upstream-dev to run on forks
  .github/workflows/upstream-dev-ci.yml
Labels: developer feature, testing
