Repository NCAR/geocat-comp, pull requests merged in 2023-06, with the labels that each got.

#417 update .pre-commit-config.yaml yapf repo
  .pre-commit-config.yaml
  docs/release-notes.rst
Labels: dependencies

#419 Reconfigure and removes src folder
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/ci.yml
  .github/workflows/upstream-dev-ci.yml
  .gitignore
  CONTRIBUTING.md
  MANIFEST.in
  docs/release-notes.rst
  geocat/__init__.py
  geocat/comp/__init__.py
  geocat/comp/climatologies.py
  geocat/comp/fourier_filters.py
  geocat/comp/gc_util.py
  geocat/comp/gradient.py
  geocat/comp/interpolation.py
  geocat/comp/meteorology.py
  geocat/comp/spherical.py
  geocat/comp/stats.py
  setup.cfg
  test/test_climatologies.py
  test/test_fourier_filters.py
  test/test_gradient.py
  test/test_interpolation.py
  test/test_meteorology.py
  test/test_spherical.py
  test/test_stats.py
Labels: refactor

#424 Issue423
  docs/release-notes.rst
  geocat/comp/interpolation.py
Labels: bug, testing

#426 Dropping support for python 3.8 and adding 3.11
  .github/workflows/ci-release.yml
  .github/workflows/ci.yml
  build_envs/docs.yml
  build_envs/environment.yml
  build_envs/upstream-dev-environment.yml
  docs/release-notes.rst
  setup.cfg
Labels: bug, dependencies, testing

#421 Remove f2py dependency
  .readthedocs.yml
  README.md
  build_envs/docs.yml
  build_envs/environment.yml
  build_envs/upstream-dev-environment.yml
  docs/getting_started/overview.rst
  docs/installation.rst
  docs/release-notes.rst
  docs/user_api/index.rst
  geocat/comp/__init__.py
  geocat/comp/deprecated.py
  requirements.txt
  setup.cfg
Labels: refactor, dependencies, deprecation

#429 Update release notes for v2023.06.0
  docs/release-notes.rst
Labels: release

#431 Remove python 3.11.0 limit
  build_envs/docs.yml
  build_envs/environment.yml
  docs/release-notes.rst
  setup.cfg
Labels: bug, dependencies
