Repository NCAR/geocat-comp, pull requests merged in 2023-03, with the labels that each got.

#357 Remove deprecated functions from v2022.10.0
  docs/internal_api/index.rst
  docs/user_api/index.rst
  src/geocat/comp/__init__.py
  src/geocat/comp/crop.py
  src/geocat/comp/eofunc.py
  src/geocat/comp/meteorology.py
  src/geocat/comp/polynomial.py
  src/geocat/comp/skewt_params.py
  test/ncl_tests/skewt_params_test.ncl
  test/skewt_params_output.nc
  test/test_meteorology.py
  test/test_polynomial.py
  test/test_skewt_params.py
Labels: refactor, ready for review, deprecation

#359 Remove links to deleted function docs
  src/geocat/comp/meteorology.py
Labels: documentation, deprecation

#341 add climatology_average example
  docs/_static/thumbnails/climatology.png
  docs/examples.rst
  docs/examples/climatology_average.ipynb
  docs/gallery.yml
  docs/installation.rst
Labels: documentation

#360 Partial fix for _vertical_remap_extrap bug
  src/geocat/comp/interpolation.py
Labels: bug, support

#361 Fix some delta_pressure docs formatting
  src/geocat/comp/meteorology.py
Labels: documentation

#362 Create a utility function to generate docstrings on wrapper functions
  docs/internal_api/index.rst
  src/geocat/comp/gc_util.py
  src/geocat/comp/meteorology.py
Labels: documentation, developer feature, ready for review

#364 Version bump v2023.03.0
  meta.yaml
Labels: ready for review, release

#365 Update release notes for v2023.03.0
  docs/release-notes.rst
Labels: ready for review, release

#339 adjust calendar example to follow similar template
  build_envs/docs.yml
  docs/examples/calendar_average.ipynb
Labels: documentation

#368 Add dpres_plev init file
  src/geocat/comp/__init__.py
Labels: bug, ready for review

#376 Update internal links to use sphinx internal referencing
  src/geocat/comp/climatologies.py
  src/geocat/comp/meteorology.py
Labels: developer feature

#390 Switch pypi release action to be triggered manually
  .github/workflows/pypi.yaml
Labels: developer feature, release

#392 Update release-notes.rst
  docs/release-notes.rst
Labels: high priority, release

#393 specify python 3.10 for pypi build
  .github/workflows/pypi.yaml
Labels: high priority, developer feature, dependencies, release

#384 Create release template
  .github/ISSUE_TEMPLATE/release.md
Labels: developer feature, ready for review
