Repository NCAR/geocat-comp, pull requests merged in 2023-10, with the labels that each got.

#485 Finalize release notes for v2023.10.0
  docs/release-notes.rst
Labels: release

#495 Update office hours link
  docs/release-notes.rst
  docs/support.rst
Labels: bug, documentation

#478 Convert unittest to pytest
  .github/workflows/ci.yml
  docs/release-notes.rst
  test/test_climatologies.py
  test/test_fourier_filters.py
  test/test_gradient.py
  test/test_interpolation.py
  test/test_meteorology.py
  test/test_spherical.py
  test/test_stats.py
Labels: blocked, testing

#436 Fix Python version in upstream CI
  build_envs/upstream-dev-environment.yml
  docs/release-notes.rst
Labels: bug, developer feature, testing

#497 Add benchmark badge to readme
  README.md
  docs/release-notes.rst
Labels: documentation, scalability and performance

#496 Connect ASV benchmarking to CI
  .github/workflows/asv-benchmarking.yml
  docs/release-notes.rst
Labels: developer feature, testing, scalability and performance

#499 Don't fail workflow for expected individual benchmarks failures
  .github/workflows/asv-benchmarking.yml
  docs/release-notes.rst
Labels: bug, testing, scalability and performance

#501 Finalize release notes for v2023.10.1
  docs/release-notes.rst
Labels: release
