Repository NCAR/geocat-comp, pull requests merged in 2023-11, with the labels that each got.

#511 Add fourier filter to comp
  docs/_static/thumbnails/fft.png
  docs/examples.rst
  docs/examples/fourier_filter.ipynb
  docs/gallery.yml
  docs/release-notes.rst
Labels: documentation, tutorial

#492 Unpin Xarray: dataArray -> dataArray.variable
  build_envs/asv-bench.yml
  build_envs/docs.yml
  build_envs/environment.yml
  docs/release-notes.rst
  geocat/comp/climatologies.py
  geocat/comp/interpolation.py
  requirements.txt
  setup.cfg
Labels: bug, support

#515 Remove no longer need numpy version pin
  build_envs/environment.yml
  docs/release-notes.rst
Labels: dependencies

#509 Remove unnecessary tag publish trigger for asv benchmark runs
  .github/workflows/asv-benchmarking.yml
  docs/release-notes.rst
Labels: bug, testing, scalability and performance

#518 Update mamba install link
  docs/contrib.rst
  docs/release-notes.rst
Labels: bug, documentation

#520 Fix extlinks formatting
  docs/conf.py
  docs/release-notes.rst
Labels: bug, documentation, dependencies, testing, deprecation

#516 EOF Unsigned Vector Tests
  docs/release-notes.rst
  test/test_stats.py
Labels: support, testing

#504 Add a note about potential type promotion to interp_multidim
  docs/release-notes.rst
  geocat/comp/interpolation.py
Labels: documentation
