Repository NCAR/geocat-comp, pull requests merged in 2023-09, with the labels that each got.

#451 Rephrase README.md
  README.md
Labels: documentation

#450 Contributor's Guide
  CONTRIBUTING.md
  docs/contrib.rst
  docs/index.rst
  docs/release-notes.rst
Labels: duplicate, developer feature

#458 Include xarray pinning in setup.cfg
  docs/release-notes.rst
  setup.cfg
Labels: dependencies

#459 Update description and fix PR links for v2023.09.0
  docs/release-notes.rst
Labels: documentation, release

#461 CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
  docs/release-notes.rst
Labels: documentation

#467 Re-add title to release notes
  docs/release-notes.rst
Labels: bug, documentation

#468 Update PR template
  .github/PULL_REQUEST_TEMPLATE.md
  docs/release-notes.rst
Labels: documentation

#476 Contributing Edits
  docs/contrib.rst
  docs/release-notes.rst
Labels: bug, documentation

#474 Set up ASV benchmarking
  .gitignore
  benchmarks/__init__.py
  benchmarks/asv.conf.json
  benchmarks/import.py
  build_envs/asv-bench.yml
  docs/release-notes.rst
Labels: developer feature, testing, scalability and performance
