Repository NCAR/geocat-comp, pull requests merged in 2023-04, with the labels that each got.

#395 Pypi packaging fix
  .github/workflows/pypi.yaml
  setup.cfg
Labels: bug, high priority, dependencies, release

#396 Limit pypi build to 3.10
  .github/workflows/pypi.yaml
Labels: bug, release

#397 Add updating release notes to pr template
  .github/ISSUE_TEMPLATE/release.md
  .github/PULL_REQUEST_TEMPLATE.md
  docs/release-notes.rst
Labels: developer feature

#385 Gradient updates with Alea
  docs/release-notes.rst
  src/geocat/comp/gradient.py
  test/test_gradient.py
Labels: bug
