Repository NCAR/geocat-comp, pull requests merged in 2024-03, with the labels that each got.

#579 pre-commit hook for codespell
  .pre-commit-config.yaml
  docs/contrib.rst
  docs/getting-started.rst
  docs/installation.rst
  docs/release-notes.rst
  docs/user_api/index.rst
  geocat/comp/climatologies.py
  geocat/comp/fourier_filters.py
  geocat/comp/interpolation.py
  geocat/comp/meteorology.py
  pyproject.toml
Labels: developer feature

#568 Move dask compatibility tests to their own testing module
  docs/release-notes.rst
  test/test_dask.py
  test/test_gradient.py
  test/test_interpolation.py
  test/test_meteorology.py
Labels: testing

#584 Geocat-comp ruff cleanup
  docs/release-notes.rst
  geocat/comp/gradient.py
  geocat/comp/meteorology.py
  test/test_climatologies.py
  test/test_dask.py
  test/test_fourier_filters.py
  test/test_gradient.py
  test/test_interpolation.py
  test/test_meteorology.py
  test/test_spherical.py
  test/test_stats.py
Labels: testing

#571 Fix delta_pressure to handle the case when pressure levels are greater than the surface pressure
  docs/release-notes.rst
  geocat/comp/meteorology.py
  test/test_meteorology.py
Labels: bug

#586 Update release notes for v2024.03.0
  docs/release-notes.rst
  test/test_dask.py
Labels: release

#587 Forgot date on release notes
  docs/release-notes.rst
Labels: release
