Repository NCAR/geocat-comp, pull requests merged in 2024-01, with the labels that each got.

#537 Update nightly wheels source
  ci/install-upstream.sh
  docs/release-notes.rst
Labels: dependencies, testing

#541 New NSF NCAR Branding
  docs/_static/images/logos/GeoCAT_nsf.svg
  docs/_static/images/logos/NSF_NCAR.png
  docs/citation.rst
  docs/conf.py
  docs/getting_started/overview.rst
  docs/index.rst
  docs/release-notes.rst
  docs/support.rst
  geocat/comp/interpolation.py
Labels: documentation

#544 Update release-notes.rst for v2024.01.0
  docs/release-notes.rst
Labels: release

#545 Logos for Light and Dark Mode
  docs/_static/images/logos/NSF_NCAR_dark.png
  docs/_static/images/logos/NSF_NCAR_light.png
  docs/conf.py
  docs/release-notes.rst
Labels: documentation
