Repository NCAR/geocat-comp, pull requests merged in 2024-02, with the labels that each got.

#548 Python 3.12 Support
  .github/workflows/ci-release.yml
  .github/workflows/ci.yml
  README.md
  build_envs/docs.yml
  build_envs/environment.yml
  docs/contrib.rst
  docs/release-notes.rst
  setup.cfg
Labels: feature

#556 Temporary pinning asv
  build_envs/asv-bench.yml
  docs/release-notes.rst
Labels: bug, dependencies, testing

#559 Add stackoverflow.com/help/* links to linkcheck_ignore
  docs/conf.py
  docs/release-notes.rst
Labels: testing

#563 Update to implicit namespace package
  MANIFEST.in
  docs/release-notes.rst
  geocat/__init__.py
  setup.cfg
Labels: refactor, developer feature, deprecation

#561 Documentation Clean Up
  docs/contrib.rst
  docs/release-notes.rst
  setup.cfg
Labels: documentation

#566 Add token to codecov upload
  .github/workflows/ci.yml
  docs/release-notes.rst
Labels: bug, developer feature, testing

#567 Unpin ASV
  build_envs/asv-bench.yml
  docs/release-notes.rst
Labels: dependencies, testing

#569 Re-pin ASV
  build_envs/asv-bench.yml
  docs/release-notes.rst
Labels: bug, dependencies, testing

#573 Update release notes for v2024.02.0
  docs/release-notes.rst
Labels: release
