Repository NCAR/geocat-comp, pull requests merged in 2024-04, with the labels that each got.

#599 Drop Python 3.9 Support
  .github/workflows/ci-release.yml
  .github/workflows/ci.yml
  build_envs/docs.yml
  build_envs/environment.yml
  docs/release-notes.rst
  setup.cfg
Labels: deprecation

#592 Address performance and deprecations in interp_hybrid_to_pressure
  docs/release-notes.rst
  geocat/comp/interpolation.py
Labels: bug, refactor, scalability and performance

#600 Pin numpy<2.0 for PyPI install issue
  build_envs/asv-bench.yml
  build_envs/environment.yml
  docs/release-notes.rst
  requirements.txt
  setup.cfg
Labels: bug, dependencies, testing

#602 Update release notes for v2024.04.0
  docs/release-notes.rst
Labels: release

#604 Add autoupdate for pre-commit hook versions
  .pre-commit-config.yaml
  docs/release-notes.rst
Labels: developer feature, dependencies, testing

#608 remove pre-commit.yml
  .github/workflows/pre-commit.yml
  docs/release-notes.rst
Labels: developer feature, testing
