Repository NCAR/geocat-comp, pull requests merged in 2025-04, with the labels that each got.

#710 Additional RH Comments
  docs/release-notes.rst
  geocat/comp/meteorology.py
Labels: developer feature

#713 Update CODE_OF_CONDUCT.md to Fix A Small Typo
  CODE_OF_CONDUCT.md
Labels: documentation

#716 Pin Third Party Github Actions
  .github/workflows/asv-benchmarking.yml
  .github/workflows/ci-release.yml
  .github/workflows/ci.yml
  .github/workflows/pypi.yaml
  .github/workflows/upstream-dev-ci.yml
  docs/release-notes.rst
Labels: developer feature

#717 Ensure compatibility with CFTime and Datetime objects for climatology functions
  docs/release-notes.rst
  geocat/comp/climatologies.py
  test/test_climatologies.py
Labels: bug

#718 Update delta_pressure docs
  docs/release-notes.rst
  geocat/comp/meteorology.py
Labels: documentation

#720 blackdoc for .rst/.md
  .pre-commit-config.yaml
  docs/release-notes.rst
Labels: documentation, developer feature
