Repository NCAR/geocat-comp, pull requests merged in 2025-03, with the labels that each got.

#699 Minimum dependency version testing and backwards compatibility
  .github/workflows/ci.yml
  build_envs/min-deps.yml
  docs/release-notes.rst
  geocat/comp/climatologies.py
  test/test_climatologies.py
Labels: developer feature, dependencies

#695 Update scipy and use `sph_harm_y`
  build_envs/asv-bench.yml
  build_envs/environment.yml
  docs/release-notes.rst
  geocat/comp/spherical.py
  requirements.txt
  setup.cfg
  test/test_spherical.py
Labels: bug, dependencies

#700 ruff formatting
  .pre-commit-config.yaml
  docs/conf.py
  docs/release-notes.rst
  geocat/comp/climatologies.py
  geocat/comp/deprecated.py
  geocat/comp/fourier_filters.py
  geocat/comp/gc_util.py
  geocat/comp/gradient.py
  geocat/comp/interpolation.py
  geocat/comp/meteorology.py
  geocat/comp/spherical.py
  geocat/comp/stats.py
  pyproject.toml
  test/test_climatologies.py
  test/test_dask.py
  test/test_fourier_filters.py
  test/test_gradient.py
  test/test_interpolation.py
  test/test_meteorology.py
  test/test_spherical.py
  test/test_stats.py
Labels: documentation, developer feature

#704 Update release notes for v2025.03.0
  docs/release-notes.rst
Labels: release
